# Generated by Django 3.0.2 on 2020-05-10 11:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('socialaccount', '0003_extra_data_default_dict'),
        ('landing', '0002_auto_20200510_1128'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='facebookpage',
            name='user',
        ),
        migrations.AddField(
            model_name='facebookpage',
            name='account',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='socialaccount.SocialAccount'),
            preserve_default=False,
        ),
    ]
