# Generated by Django 3.0.2 on 2020-06-21 14:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('landing', '0003_auto_20200510_1137'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='facebookpage',
            name='account',
        ),
    ]
