# Generated by Django 3.0.2 on 2020-06-21 15:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reporting', '0008_auto_20200621_1552'),
        ('landing', '0004_remove_facebookpage_account'),
    ]

    operations = [
        migrations.DeleteModel(
            name='FacebookPage',
        ),
    ]
