# Generated by Django 3.0.2 on 2020-04-29 14:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('landing', '0001_initial'),
        ('reporting', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='FacebookReport',
            new_name='FacebookPageReport',
        ),
        migrations.RemoveField(
            model_name='facebookpagereport',
            name='post',
        ),
        migrations.AddField(
            model_name='facebookpagereport',
            name='page',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='landing.FacebookPage'),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='FacebookPostReport',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('impressions', models.IntegerField()),
                ('engagement', models.IntegerField()),
                ('date', models.DateField()),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reporting.FacebookPost')),
            ],
        ),
    ]
