# Generated by Django 3.0.2 on 2020-04-30 16:23

from django.db import migrations, models
import django.db.models.deletion
import datetime

class Migration(migrations.Migration):

    dependencies = [
        ('landing', '0001_initial'),
        ('reporting', '0002_auto_20200429_1412'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='facebookpost',
            name='date',
        ),
        migrations.AddField(
            model_name='facebookpost',
            name='created_time',
            field=models.DateTimeField(default=datetime.datetime.now()),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='facebookpost',
            name='page',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='landing.FacebookPage'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='facebookpost',
            name='post_id',
            field=models.CharField(default=1, max_length=2048),
            preserve_default=False,
        ),
    ]
