# Generated by Django 3.0.2 on 2020-05-12 11:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('reporting', '0004_auto_20200430_1656'),
    ]

    operations = [
        migrations.CreateModel(
            name='FacebookComment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_time', models.DateTimeField()),
                ('content', models.CharField(max_length=2048)),
                ('comment_id', models.CharField(max_length=2048, unique=True)),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reporting.FacebookPost')),
            ],
        ),
    ]
