# Generated by Django 3.0.2 on 2020-05-25 20:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reporting', '0005_facebookcomment'),
    ]

    operations = [
        migrations.AddField(
            model_name='facebookpostreport',
            name='sentiment',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
    ]
