# Generated by Django 3.0.2 on 2020-05-25 21:26

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reporting', '0006_facebookpostreport_sentiment'),
    ]

    operations = [
        migrations.RemoveField(
             model_name='facebookpostreport',
            name='sentiment',
        ),
        migrations.AddField(
            model_name='facebookpostreport',
            name='sentiment',
            field=django.contrib.postgres.fields.jsonb.JSONField(),
        ),
    ]
