# Generated by Django 3.0.2 on 2020-06-21 15:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('socialaccount', '0003_extra_data_default_dict'),
        ('reporting', '0007_auto_20200525_2126'),
    ]

    operations = [
        migrations.CreateModel(
            name='FacebookPage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('page_id', models.CharField(max_length=2048, unique=True)),
                ('access_token', models.CharField(max_length=2048)),
                ('name', models.CharField(max_length=248)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='socialaccount.SocialAccount')),
            ],
        ),
        migrations.CreateModel(
            name='UserPreferences',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('business_category', models.CharField(max_length=128)),
                ('fav_page', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reporting.FacebookPage')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AlterField(
            model_name='facebookpagereport',
            name='page',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reporting.FacebookPage'),
        ),
        migrations.AlterField(
            model_name='facebookpost',
            name='page',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reporting.FacebookPage'),
        ),
    ]
