# Generated by Django 3.0.2 on 2020-06-21 17:47

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('reporting', '0008_auto_20200621_1552'),
    ]

    operations = [
        migrations.AlterField(
            model_name='facebookpostreport',
            name='post',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='reporting.FacebookPost'),
        ),
        migrations.AlterField(
            model_name='facebookpostreport',
            name='sentiment',
            field=django.contrib.postgres.fields.jsonb.JSONField(null=True),
        ),
    ]
