# Generated by Django 3.0.2 on 2020-06-21 19:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reporting', '0009_auto_20200621_1747'),
    ]

    operations = [
        migrations.AddField(
            model_name='facebookpost',
            name='hour',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='facebookpost',
            name='post_type',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='facebookpost',
            name='week_day',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='facebookpostreport',
            name='reach',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='facebookpostreport',
            name='reactions',
            field=models.IntegerField(default=0),
        ),
    ]
