# Generated by Django 3.0.2 on 2020-06-21 21:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('reporting', '0010_auto_20200621_1959'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userpreferences',
            name='business_category',
            field=models.CharField(max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='userpreferences',
            name='fav_page',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='reporting.FacebookPage'),
        ),
    ]
