# Generated by Django 3.0.2 on 2020-06-22 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reporting', '0011_auto_20200621_2238'),
    ]

    operations = [
        migrations.AddField(
            model_name='facebookpost',
            name='comments_synced',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='facebookpost',
            name='nb_comments',
            field=models.IntegerField(default=0),
        ),
    ]
