# Generated by Django 3.0.2 on 2020-06-22 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reporting', '0012_auto_20200622_1327'),
    ]

    operations = [
        migrations.AddField(
            model_name='facebookpost',
            name='link',
            field=models.CharField(max_length=2048, null=True),
        ),
    ]
